### ISSUE TITLE
Register Contract API for Fabric Stack fails with 400 Bad Request Error.

### ISSUE THREAD

**Issue by jsolderitsch** [hyperledger/firefly-sandbox#90]
![Screen Shot 2022-05-15 at 10 53 32 PM](https://user-images.githubusercontent.com/23091236/168606925-3c64f298-05b0-4307-804f-c9f83d4ef03b.png)
This is the failure I see. Cutting and pasting from the Server Response:
```
{
 
"name"
: 
"BadRequestError"
,
 
"message"
: 
"Invalid body, check 'errors' property for more info."
,
 
"stack"
: 
"Error\n    at new HttpError (/app/server/node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)\n    at new BadRequestError (/app/server/node_modules/routing-controllers/cjs/http-error/BadRequestError.js:10:9)\n    at /app/server/node_modules/routing-controllers/cjs/ActionParameterHandler.js:206:31\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ActionParameterHandler.normalizeParamValue (/app/server/node_modules/routing-controllers/cjs/ActionParameterHandler.js:126:21)\n    at async Promise.all (index 0)"
,
 
"errors"
: [
  {
   
"target"
: {
    
"name"
: 
"assetTransfer"
,
    
"interfaceName"
: 
"asset_transfer"
,
    
"interfaceVersion"
: 
"1.0"
,
    
"chaincode"
: 
"asset_transfer"
,
    
"channel"
: 
"firefly"

   },
   
"property"
: 
"address"
,
   
"children"
: [],
   
"constraints"
: {
    
"isString"
: 
"address must be a string"

   }
  }
 ]
}
```
The API creation succeeds with postman. The FFI is the one used in the draft tutorial document. The contract was deployed with the CLI.

**Comment by eberger727** [comment]
#91
