### ISSUE TITLE
Sandbox UI is not working properly due to verifiers api not working

### ISSUE THREAD

**Issue by Chengxuan** [hyperledger/firefly-sandbox#96]
ff version:
```
{
  "Version": "1.1.0-alpha.2",
  "Commit": "cf3f1f682394dde73c11ea07964d4285651460b5",
  "Date": "2022-07-25T14:01:03Z",
  "License": "Apache-2.0"
}
```

## Screenshot

![image](https://user-images.githubusercontent.com/5425125/184126699-d379f167-4785-4a4c-a1c2-e093550bea5e.png)

dev_sandbox_0 logs:
```
> firefly-sandbox-server@0.1.0-alpha.1 start
> node .

UI Served from /app/ui/build
Application listening on port 3001
2022-08-11T11:25:14.388Z [SimpleWebSocket] Connecting websocket client L8NxV7KrjMaejK9hWcEHT
2022-08-11T11:25:44.719Z [FireFlyWebSocket] Connection restored
2022-08-11T11:26:02.088Z [SimpleWebSocket] Connecting websocket client FsdUcgjIyCTVxrpKKKYjJ
2022-08-11T11:26:02.159Z [FireFlyWebSocket] Connected
2022-08-11T11:25:14.447Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:14.449Z [FireFlyWebSocket] Websocket closed: Closed by peer
2022-08-11T11:25:19.492Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:19.493Z [FireFlyWebSocket] Websocket closed: Closed by peer
2022-08-11T11:25:24.516Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:24.519Z [FireFlyWebSocket] Websocket closed: Closed by peer
2022-08-11T11:25:29.573Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:29.575Z [FireFlyWebSocket] Websocket closed: Closed by peer
2022-08-11T11:25:34.616Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:34.620Z [FireFlyWebSocket] Websocket closed: Closed by peer
2022-08-11T11:25:39.668Z [FireFlyWebSocket] Error Error: connect ECONNREFUSED 192.168.65.2:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
2022-08-11T11:25:39.670Z [FireFlyWebSocket] Websocket closed: Closed by peer
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error
    at new HttpError (/app/server/node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new InternalServerError (/app/server/node_modules/routing-controllers/cjs/http-error/InternalServerError.js:10:9)
    at FireFly.errorHandler (/app/server/dist/src/clients/firefly.js:10:11)
    at /app/server/node_modules/@hyperledger/firefly-sdk/dist/http.js:40:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error
    at new HttpError (/app/server/node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new InternalServerError (/app/server/node_modules/routing-controllers/cjs/http-error/InternalServerError.js:10:9)
    at FireFly.errorHandler (/app/server/dist/src/clients/firefly.js:10:11)
    at /app/server/node_modules/@hyperledger/firefly-sdk/dist/http.js:40:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error
    at new HttpError (/app/server/node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new InternalServerError (/app/server/node_modules/routing-controllers/cjs/http-error/InternalServerError.js:10:9)
    at FireFly.errorHandler (/app/server/dist/src/clients/firefly.js:10:11)
    at /app/server/node_modules/@hyperledger/firefly-sdk/dist/http.js:40:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/app/server/node_modules/send/index.js:390:13)
    at SendStream.send (/app/server/node_modules/send/index.js:617:10)
    at onstat (/app/server/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
```

**Comment by Chengxuan** [comment]
I think this could be caused by https://github.com/hyperledger/firefly/issues/952 FYI @awrichar

**Comment by awrichar** [comment]
@Chengxuan It might also be that we haven't migrated the sandbox to use APIs that were recently changed: https://github.com/hyperledger/firefly/wiki/Migration-Guide-for-v1.1.0#less-common-situations

**Comment by shorsher** [comment]
@Chengxuan, thanks for great info you provided. After merging https://github.com/hyperledger/firefly-sandbox/pull/97, I was not able to reproduce this issue running locally on my laptop. @awrichar or @Chengxuan, would you mind verifying with the latest version of FF?
